document.writeln("");
document.writeln("<div class=\'list\' style=\'background: url(./images/1_02.jpg);\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <ul id=\'mytab\' class=\'nav nav-tabs nav-pills nav-justified\'>");
document.writeln("        <li role=\'presentation\'>");
document.writeln("          <a href=\'index.html\'>主页</a>");
document.writeln("        </li>");
document.writeln("        <li role=\'presentation\'>");
document.writeln("          <a href=\'company-show.html\'>公司简介</a>");
document.writeln("        </li>");
document.writeln("        <li role=\'presentation\'>");
document.writeln("          <a href=\'product-show-p-1.html\'>产品展示</a>");
document.writeln("        </li>");
document.writeln("        <li role=\'presentation\'>");
document.writeln("          <a href=\'product-img.html\'>产品图片</a>");
document.writeln("        </li>");
document.writeln("        <li role=\'presentation\'>");
document.writeln("          <a href=\'patent-show.html\'>专利展示</a>");
document.writeln("        </li>");
document.writeln("        <li role=\'presentation\'>");
document.writeln("          <a href=\'news.html\'>新闻动态</a>");
document.writeln("        </li>");
document.writeln("        <li role=\'presentation\'>");
document.writeln("          <a href=\'phone.html\'>联系我们</a>");
document.writeln("        </li>");
document.writeln("<li role=\'presentation\'>");
document.writeln("          <a href=\'phone.html\'>联系我们</a>");
document.writeln("        </li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("  </div>");